// Generated by https://quicktype.io

export interface DataProject {
  data: Data;
}

export interface Data {
  projectName: string;
  location: string;
  LatLong: number[];
  city: string;
  state: string;
  country: string;
  price: number;
  añoEntrega: number;
  introducingVideo: string;
  images: string[];
  drawingsProject: string[];
  drawingsApartment: string[];
  apartmentDetails: ApartmentDetails;
  projectDetails: ProjectDetails;
  paymentMethod: PaymentMethod;
}

export interface ApartmentDetails {
  areaConstruida: number;
  areaPrivada: number;
  estado: string;
  alcobas: number;
  banos: number;
  garajes: string;
  caracteristicaGaraje: string;
  tipoGaraje: string;
  estrato: number;
  balcon: boolean;
  areaBalcon: number;
  acabados: string;
  nivelesInmueble: number;
  salaComedor: string;
  calentadorAgua: string;
  vista: string;
  bañoSocial: boolean;
  estudio: boolean;
  gasNatural: boolean;
  zonaRopas: string;
}

export interface PaymentMethod {
  separacion: number;
  cuotaInicial: number;
  saldoFinanciar: number;
  banco: string;
  cuotas: Cuota[];
}

export interface Cuota {
  plazoAños: number;
  cuotaMensual: number;
}

export interface ProjectDetails {
  estado: string;
  pisosTorre: number;
  torres: number;
  ascensorTorre: number;
  apartamentosPiso: number;
  relacionParqueaderos: string;
  fechaEntrega: string;
  bbq: boolean;
  bicicleteros: boolean;
  canchaMultiple: boolean;
  conjunto: string;
  coworking: boolean;
  gimnasio: boolean;
  parqueInfantil: boolean;
  juegosInfantiles: boolean;
  lobby: boolean;
  parqueaderoVisitantes: boolean;
  piscina: boolean;
  porteria: boolean;
  recepcion: boolean;
  salonComunal: boolean;
  salonJuegos: boolean;
  salonInfantil: boolean;
  salonSocial: boolean;
  shut: boolean;
  petFriendly: boolean;
}
